services:
  - type: web
    name: research-brief-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.api:app
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: true
      - key: LANGCHAIN_ENDPOINT
        value: https://api.smith.langchain.com
      - key: LANGCHAIN_PROJECT
        value: research-brief-generator
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./research_briefs.db
      - key: API_HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
